module.exports = [
  "Naps-Member",
  "President",
  "Vice President",
  "Editors-In-Chief",
  "Media Head",
  "Epistle Head",
  "Events' Head",
  "Interviews' Head",
  "Technical Head",
  "Senior Executive Member",
  "General Secretary",
  "Joint-Secretary",
  "Treasure",
  "Joint Treasurer",
  "Deputy Editor",
  "Media Coordinator",
  "Epistle Coordinator",
  "Interviews' Coordinator",
  "Events' Coordinator",
  "Design Head",
  "Technical Coordinator",
  "Executive Member",
];
